### ISSUE TITLE
Pronunciation video on Twitter is not available

### ISSUE THREAD

**Issue by rybak** [foosel/foosel#1]
README.md links to https://twitter.com/foosel/status/1316753643077611520, which can't be viewed by public, because account [@foosel](https://twitter.com/foosel/) is "protected".

![Screenshot of the tweet in question in Firefox](https://user-images.githubusercontent.com/624072/216771440-10f93b1c-d917-4192-aae3-67c3ac907b2b.png)

**Comment by foosel** [comment]
Thanks for the heads-up, I've replaced it with a link to an mp3 on my website.
